name: Deploy with Approval

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Application
        run: echo "Building application..."

  approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Await Approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          approvers: 'piotr.s.koska@gmail.com'  # Podaj GitHub username osoby zatwierdzającej
          minimum-approvals: 1
          secret: ${{ github.PERSONAL_ACCESS_TOKEN }}
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
          timeout-minutes: 60

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Deploy Application
        run: echo "Deploying application..."
