name: Test akceptacji

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Application
        run: echo "Building application..."

  approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Await Approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          approvers: 'TheRealMamuth'  # Podaj GitHub username osoby zatwierdzającej
          minimum-approvals: 1
          secret: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          issue-title: "Akceptacja wdrożenia wersji v1.3.5"
          issue-body: "Prosze o zatwierdzenie wdrożenia wersji v1.3.5"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'TAK,tak'
          additional-denied-words: 'NIE,nie'
          timeout-minutes: 60

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Deploy Application
        run: echo "Deploying application..."
