name: Deploy with Approval

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Application
        run: echo "Building application..."

  approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Await Approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          approvers: 'piotr.s.koska@gmail.com'  # Podaj GitHub username osoby zatwierdzającej
          minimum-approvals: 1

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Deploy Application
        run: echo "Deploying application..."
