name: Deploy with In-Workflow Approval

on:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building application..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Await Approval
        uses: fjogeleit/manual-approval-action@v1
        with:
          approvers: 'twoje_uzytkowniki'  # możesz podać użytkowników, którzy muszą zatwierdzić
          comment: 'Please approve to proceed with the deployment.'

      - name: Deploy Application
        if: ${{ steps.approval.outcome == 'approved' }}
        run: echo "Deploying application..."
