name: Deploy with Approval

on:
  workflow_dispatch:
    inputs:
      approve_deploy:
        description: 'Approve deployment'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building application..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.inputs.approve_deploy == 'yes' }}
    steps:
      - name: Deploy Application
        run: echo "Deploying application..."
